################
### MONITORS ###
################
monitor=LVDS-1,preferred,0x0,1
monitor=VGA-1,preferred,1366x0,1
monitor=HDMI-A-1,1366x768,auto,1,mirror,LVDS-1

#############################
### ENVIRONMENT VARIABLES ###
#############################
env = XCURSOR_THEME, capitaine-cursors
env = XCURSOR_SIZE,16
env = HYPRCURSOR_THEME, capitaine-cursors
env = HYPRCURSOR_SIZE,16
env = XDG_CURRENT_DESKTOP, Hyprland

########################
### WORKSPACE RULES ###
########################
# Odd numbered workspaces on main monitor
workspace = 1, monitor:LVDS-1, default:true
workspace = 3, monitor:LVDS-1
workspace = 5, monitor:LVDS-1
workspace = 7, monitor:LVDS-1
workspace = 9, monitor:LVDS-1

# Even numbered workspaces on secondary monitor
workspace = 2, monitor:VGA-1, default:true
workspace = 4, monitor:VGA-1
workspace = 6, monitor:VGA-1
workspace = 8, monitor:VGA-1
workspace = 10, monitor:VGA-1

###################
### PERMISSIONS ###
###################
permission = /usr/(bin.config/hypr/scripts)/grim, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/(bin.config/hypr/scripts)/hyprpm, plugin, allow
